# Generated by Django 3.1.5 on 2021-01-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblBillingMonths',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tbl_billingmonths',
            },
        ),
        migrations.CreateModel(
            name='tblFeeders',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('div', models.CharField(max_length=50)),
                ('subDiv', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_feeders',
            },
        ),
        migrations.CreateModel(
            name='tblTariffs',
            fields=[
                ('tariffID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('slab1Rate', models.FloatField(default=0)),
                ('slab2Rate', models.FloatField(default=0)),
                ('slab3Rate', models.FloatField(default=0)),
                ('singlePhMeterRent', models.FloatField(default=0)),
                ('threePhMeterRent', models.FloatField(default=0)),
                ('TVFee', models.FloatField(default=0)),
                ('EDuty', models.FloatField(default=0)),
                ('GST', models.FloatField(default=0)),
                ('NJS', models.FloatField(default=0)),
                ('FCS', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'tbl_tariffs',
            },
        ),
        migrations.CreateModel(
            name='tblSchedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readingDate', models.CharField(default='15', max_length=10)),
                ('issueDate', models.CharField(default='15', max_length=10)),
                ('feederName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.tblfeeders')),
                ('monthName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.tblbillingmonths')),
            ],
            options={
                'db_table': 'tbl_schedules',
            },
        ),
    ]
