# Generated by Django 3.1.5 on 2021-01-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0002_tblfeeders_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblfeeders',
            name='area',
        ),
    ]
