# Generated by Django 3.1.5 on 2021-01-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20210128_2045'),
        ('baseApp', '0003_remove_tblfeeders_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblschedules',
            name='feederName',
        ),
        migrations.RemoveField(
            model_name='tblschedules',
            name='monthName',
        ),
        migrations.DeleteModel(
            name='tblBillingMonths',
        ),
        migrations.DeleteModel(
            name='tblSchedules',
        ),
    ]
