# Generated by Django 3.1.1 on 2021-02-02 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_auto_20210128_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblfeeders',
            name='dueDate',
        ),
    ]
