# Generated by Django 3.1.5 on 2021-01-26 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='tblMeters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meterType', models.CharField(max_length=50)),
                ('connectionType', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('installationDate', models.DateField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=0)),
                ('feederName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.tblfeeders')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'tbl_meters',
            },
        ),
        migrations.CreateModel(
            name='tblBills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousReading', models.FloatField(default=0)),
                ('currentReading', models.FloatField(default=0)),
                ('units', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('status', models.CharField(max_length=10)),
                ('paidDate', models.CharField(default='1234:12:31', max_length=20)),
                ('billingMonth', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.tblbillingmonths')),
                ('meterID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='userApp.tblmeters')),
                ('tariffID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='baseApp.tbltariffs')),
            ],
            options={
                'db_table': 'tbl_bills',
            },
        ),
    ]
