# Generated by Django 3.1.5 on 2021-01-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20210127_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbills',
            name='billingMonth',
            field=models.CharField(default='jan', max_length=50),
        ),
    ]
