# Generated by Django 3.1.1 on 2021-02-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_remove_tblbills_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbills',
            name='dueDate',
            field=models.CharField(default='1234:12:31', max_length=20),
        ),
    ]
